name: innotrash
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/photos/bg_home.png
    - assets/photos/profile_pic.png
    - assets/photos/bg_1.png
    - assets/photos/bg_2.png
    - assets/photos/bg_3.png
    - assets/photos/bg_4.png
    - assets/photos/bg_qr.png
    - assets/photos/map.png
    - assets/photos/map_home.png
    - assets/photos/rewardsone_image.png
    - assets/photos/rewardstwo_image.png
    - assets/photos/rewardsthree_image.png
    - assets/photos/rewardsfour_image.png
    - assets/photos/rewardsfive_image.png
    - assets/photos/rewardssix_image.png
    - assets/photos/intro_1.png
    - assets/photos/intro_2.png
    - assets/photos/intro_3.png

  fonts:
    - family: Sans Serif
      fonts:
        - asset: assets/fonts/BebasNeue.otf
